---
title: "Mobile Health Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    horizontal_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(igraph)
```

Column {.sidebar data-width=250}
-------------------------------------
### **Patient Information**
**Name:** xxx

**Age:** xx

**Gender:** xx

**Study length:** 2 weeks

### **Description**

**Fig.1** shows the trends of the number of both incoming and outgoing phone calls per day in the past week, and the maximum number of calls in the whole study period. 

**Fig.2** shows the social network through phones in the past week. And each line connection between two subjects indicates one-time phone call. 

**Fig.3** shows the percent of number of phone calls during different time part of the day in the past week. (Note: morning: 5:00 to 12:00; afternoon: 12:00 to 17:00; evening: 17:00 to 21:00; night: 21:00 to 5:00.)

**Fig.4** shows the weekly trends in daily self-report of social activity score. (Note: The self-assessment result range from 0 to 3, where 0 means no social activity at all and 3 means extremely high social active.)

**Fig.5** shows the weekly trends in daily self-report of loneliness. (Note: The self-assessment result range from 0 to 3, where 0 means extremely lonely and 3 means not lonely at all.)

**Table.1** indicates the maximum, minimum, mean, and the latest visit of the psychiatric socre measured in clinic.

Row {data-height=400}
-------------------------------------

### **Fig.1 Number of Call per Day in the Past Week**
```{r}
data = read.csv("./data/simulate_data.csv")
nocall = which(data$Time == ".")
data[,8] = 1
data[nocall,8] = 0

total = data %>% 
  group_by(Date, In_Out) %>% 
  summarise(count = sum(V8))

max_in = total %>% 
  filter(In_Out == "in")  
max_incoming = max(max_in$count)

max_out = total %>% 
  filter(In_Out == "out")  
max_outgoing = max(max_out$count)

week_index = which(data$Date == "9/9/19")[[1]]
week_data = data[week_index:nrow(data),] %>% 
  mutate(Date = as.character(Date)) %>% 
  mutate(Date = replace(Date, Date == "9/9/19", 1),
         Date = replace(Date, Date == "9/10/19", 2),
         Date = replace(Date, Date == "9/11/19", 3),
         Date = replace(Date, Date == "9/12/19", 4),
         Date = replace(Date, Date == "9/13/19", 5),
         Date = replace(Date, Date == "9/14/19", 6),
         Date = replace(Date, Date == "9/15/19", 7))
         
week_data_in = week_data %>%
  filter(In_Out %in% c(".", "in")) %>% 
  group_by(Date) %>%
  summarise(count = sum(V8)) %>% 
  mutate(Date = as.numeric(Date))

week_data_out = week_data %>%
  filter(In_Out %in% c(".", "out")) %>% 
  group_by(Date) %>%
  summarise(count = sum(V8)) %>% 
  mutate(Date = as.numeric(Date))

date = cbind(Date = c(1:7), count = c(1:7)) %>% as.data.frame()

pastweek = merge(week_data_in, week_data_out, by = "Date", all = TRUE) %>% 
  merge(., date, by = "Date", all = TRUE) %>% 
  select(-count) %>% 
  gather(key = in_out, value = count, count.x:count.y)
pastweek[is.na(pastweek)] <- 0
  
pastweek %>% 
  ggplot(aes(x = Date, y = count, col = in_out)) +
  geom_line() +
  geom_line(aes(y = max_incoming, col = "Max Incoming")) +
  geom_line(aes(y = max_outgoing, col = "Max Outgoing")) +
  scale_x_discrete(limit = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")) + 
  theme(text = element_text(size=20),
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.text = element_text(size = 15)) +
  scale_fill_discrete(labels = c("Incoming", "Outgoing", "Max Incoming", "Max Outgoing")) +
  labs(
    x = "Weekday",
    y = "Number of Call"
  )
```

### **Fig.2 Social Network for the Past Week**
```{r, fig.height=5,fig.width=5}
network_data = week_data %>% 
  filter(Person != ".") %>% 
  select(Subject, Person) %>% 
  mutate(Subject = as.character(Subject),
         Person = as.character(Person))

net = graph.data.frame(network_data, directed = FALSE)
V(net)$label = V(net)$name
V(net)$degree = degree(net)
set.seed(125)
plot(net,
     vertex.color = "#F0E442",
     vertex.size = 30,
     edge.arrow.size = 1.5)
```   

### **Fig.3 Percent of Calls for Different Part of the Day**
```{r}
percent_data = week_data %>% 
  filter(Time != ".") %>% 
  mutate(Time = str_replace(Time, ":", "."),
         Time = as.numeric(Time)) %>% 
  mutate(Period = ifelse(Time > 5 & Time <= 12, "morning",
                  ifelse(Time > 12 & Time <= 17, "afternoon",
                  ifelse(Time > 17 & Time <= 21, "evening", "night"))),
         Period = factor(Period, levels = c("morning", "afternoon", "evening", "night"))) 
num = nrow(percent_data)

percent <- function(x, digits = 1, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "%")
}

percent_data %>% 
  group_by(Period) %>% 
  summarise(Percent = percent(n()/num)) %>% 
  ggplot(aes(x = Period, y = Percent)) +
  geom_bar(stat = "identity", fill = "#0072B2", width = 0.5) +
  theme(text = element_text(size=20)) +
  labs(
    x = "Part of the Day",
    y = "Percent of Total Calls"
  )
```

Row {data-height=400}
-------------------------------------

```{r, fig.height=2.6,fig.width=6}
week_data %>% 
  group_by(Date) %>% 
  summarise(num = n(),
            value = sum(Social_Active_Score)/num) %>% 
  select(-num) %>%
  mutate(Date = as.numeric(Date)) %>% 
  ggplot(aes(x = Date, y = value)) +
  geom_line(color = "#56B4E9") +
  scale_x_discrete(limit = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")) +
  scale_y_discrete(limit = c(0,1,2,3)) +
  labs(
    title = "Fig.4 Daily Social Activity Score",
    x = "Weekday",
    y = "Social Active Score"
  )
```


```{r, fig.height=2.6,fig.width=6}
week_data %>% 
  group_by(Date) %>% 
  summarise(num = n(),
            value = sum(Loneliness_Score)/num) %>% 
  select(-num) %>%
  mutate(Date = as.numeric(Date)) %>% 
  ggplot(aes(x = Date, y = value)) +
  geom_line(color = "#66CC99") +
  scale_x_discrete(limit = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")) +
  scale_y_discrete(limit = c(0,1,2,3)) +
  labs(
    title = "Fig.5 Daily Loneliness Score",
    x = "Weekday",
    y = "Loneliness Score"
  )
```   

Row {data-height=200}
-------------------------------------
### **Table.1 Psychiatric Score in Clinic**
```{r}
data.frame(Max = 5, Min = 1, Mean = 3, Last_visit = 4) %>% 
  knitr::kable()
```